<div id="background">
    <div id="movebg"></div>
    <div id="page">
      <div id="header">
        <span id="connect"><a href="#" class="facebook"></a> <a href="#" class="twitter"></a> <a href="#" class="vimeo"></a></span> <span id="infos"><a href="login.php">Login</a>|<a href="signup.php">Register here!</a></span> <a href="index.php" id="logo"></a> <!-- /#logo -->
        <ul id="navigation">
          <li>
            <a href="index.php">Home</a>
          </li>
          <li class="selected">
            <a href="about.php">About</a>
          </li>
          <li>
            <a href="product.php">Shop</a>
          </li>
          <li>
            <a href="enquire.php">Enquire</a>
          </li>
          <li>
            <a href="contact-us.php">Contact</a>
          </li>
        </ul>
      </div><!-- /#header -->
      <div id="contents">
        <div id="main">
          <div id="adbox"><img src="images/sale_4.jpg" alt="sale_4"></div><br>
          <h1>We Strive to Pioneer the Creation of the Best Quality Shoes</h1><br>
          <p>The ShoesRoom is a business that values innovation, growth, and purpose. We believe that the success of our teammates promotes the success of our company as we work to better society through sport. This is demonstrated by our continued dedication to fostering an atmosphere that prioritizes respect, equality, and inclusion. When our teams experience encouragement and inspiration, they are more creative and innovative and more likely to meet our objectives and assist our athletes worldwide. When each member of our team feels valued, appreciated, and heard, everyone can be themselves and give their all each and every day, and The ShoesRoom is at its best.</p>
          <h1>Sales Motto:</h1>
          <p>We hope the shoes will be covered everywhere in the country, to every corner to take better care of your health</p>
          <h1>Become our Partners</h1>
          <p>We always welcome investors and supporters everywhere. We hope that our message will always be supported by customers and partners</p>
        </div>
        <div id="featured">
          <ul>
            <li><img src="images/shoes4a.jpg" alt="shoes4"></li>
            <li><img src="images/shoes1a.jpg" alt="shoes1"></li>
            <li><img src="images/shoes5a.jpg" alt="shoes5"></li>
            <li class="last"><img src="images/shoes8a.jpg" alt="shoes8"></li>
          </ul><a href="product.php" class="button">shop here!</a>
        </div>
      </div><!-- /#contents -->
      <div id="footer">
        <div id="description">
          <div>
            <a href="index.php" class="logo"></a>
          </div>
          <p>We're The Shoesroom from class COS10026.2 at Swinburne University. My team has 4 members who are Tran Hoang Hai Anh, Nguyen Tuan Duc, Nguyen Manh Dung and Nguyen Tran Yen Binh. Our group decided to create a web selling shoes. We built this website to provide customers another option for a shoes sale website since there is a high demand for the footwear business and there are now only a few websites selling shoes worldwide.</p>
        </div>
        <div class="navigation">
          <a href="index.php">Home</a>| <a href="about.php">About</a>|<a href="product.php">Shop</a>|  <a href="enquire.php">Enquire</a>| <a href="contact-us.php">Contact</a>
        </div>
      </div><!-- /#footer -->
    </div><!-- /#page -->
  </div>