<div id="footer">
        <div id="description">
          <div>
            <a href="index.php" class="logo"></a>
          </div>
          <p>We're The Shoesroom from class COS10026.2 at Swinburne University. My team has 4 members who are Tran Hoang Hai Anh, Nguyen Tuan Duc, Nguyen Manh Dung and Nguyen Tran Yen Binh. Our group decided to create a web selling shoes. We built this website to provide customers another option for a shoes sale website since there is a high demand for the footwear business and there are now only a few websites selling shoes worldwide.</p>
        </div>
        <div class="navigation">
          <a href="index.php">Home</a>| <a href="enhancement.php">Enhancement</a>|<a href="product.php">Shop</a>| <a href="enquire.php">Enquire</a>|  <a href="contact-us.php">Contact</a>
        </div>
      </div>