<div id="header">
         <span id="connect"><a href="#" class="facebook"></a> <a href="#" class="twitter"></a> <a href="#" class="vimeo"></a></span> <span id="infos"><a href="login.php">Login</a>|<a href="signup.php">Register here !</a></span> <a href="index.php" id="logo"></a> <!-- /#logo -->
        <ul id="navigation">
          <li >
            <a href="index.php">Home</a>
          </li>
          <li>
            <a href="enhancement.php">Enhancement</a>
          </li>
          <li>
            <a href="product.php">Shop</a>
          </li>
          <li>
            <a href="enquire.php">Enquire</a>
          </li>
          <li>
            <a href="contact-us.php">Contact</a>
          </li>
        </ul>
      </div>