<div id="background">
  <div id="movebg"></div>
  <div id="page">
    <div id="header"> <span id="connect"> <a href="#" class="facebook"></a> <a href="#" class="twitter"></a> <a href="#" class="vimeo"></a> </span> <span id="infos"> <a href="login.php">Login</a>|<a href="signup.php">Register here !</a> </span> <a href="index.php" id="logo"></a>
      <!-- /#logo -->
      <ul id="navigation">
        <li><a href="index.php">Home</a></li>
        <li><a href="enhancement.php">Ehancement</a></li>
        <li class="selected"><a href="product.php">Shop</a></li>
        <li><a href="enquire.php">Enquire</a></li>
        <li><a href="contact-us.php">Contact</a></li>
      </ul>
    </div>
    <!-- /#header -->
    <div id="contents">
      <h1>Welcome to The Shoesroom</h1>
        <h2>Great shoes, great price, great quality</h2>
        <div id="adbox"> <img src="images/sale_3.jpg" alt=""></div><br>
      <div id="shop">
        <section>
        <ul class="items">
          <li> <span class="shoe_img"><img src="images/shoes1a.jpg" alt="">
            <p>
            Gender: Unisex <br>
            Size run: 35 – 46 <br>
            Upper: All Suede <br>
            Outsole: Rubber <br>
            </p>
        </span> <span class="price">1.090.000 VND</span> TRACKER <br>
            <a href="enquire.php" class="buy">Buy</a> </li>
          <li> <span class="shoe_img"><img src="images/shoes2a.jpg" alt="">
            <p> 
              Gender: Unisex <br>
              Size run: 35 – 46 <br>
              Upper: Leather/Suede <br>
              Outsole: ICY Rubber <br>
              Including a mystery box <br>
            </p>
          </span> <span class="price">1.490.000 VND</span> UTILITY <br><br>
            <a href="enquire.php" class="buy">Buy</a> </li>
          <li> <span class="shoe_img"><img src="images/shoes3a.jpg" alt="">
            <p> 
              Gender: Unisex <br>
              Size run: 35 – 46 <br>
              Upper: Suede <br>
              Outsole: Rubber <br>
            </p>
          </span> <span class="price">720.000 VND</span> VINTAS <br>
            <a href="enquire.php" class="buy">Buy</a> </li>
          <li class="last"> <span class="shoe_img"><img src="images/shoes5a.jpg" alt="">
            <p> 
              Gender: Unisex <br>
              Size run: 35 – 46 <br>
              Upper: Canvas NE <br>
              Outsole: Rubber <br>
            </p>
          </span> <span class="price">580.000 VND</span> BASAS <br>
            <a href="enquire.php" class="buy">Buy</a> </li>
          <li> <span class="shoe_img"><img src="images/shoes4a.jpg" alt="">
            <p> 
              Gender: Unisex <br>
              Size run: 35 – 46 <br>
              Upper: Canvas NE <br>
              Outsole: Rubber <br>
              Included an extra set of laces <br>
            </p>
          </span> <span class="price">580.000 VND</span> URBAS <br>
            <a href="enquire.php" class="buy">Buy</a> </li>
          <li> <span class="shoe_img"><img src="images/shoes6a.jpg" alt="">
            <p> 
              Gender: Unisex <br>
              Size run: 35 – 46 <br>
              Upper: Canvas NE <br>
              Outsole: Rubber <br>
            </p>
          </span> <span class="price">650.000 VND</span> MULE <br><br>
            <a href="enquire.php" class="buy">Buy</a> </li>
          <li> <span class="shoe_img"><img src="images/shoes7a.jpg" alt="">
            <p> 
              Gender: Unisex <br>
              Size run: 35 – 46 <br>
              Upper: Canvas <br>
              Outsole: Rubber <br>
            </p>
          </span> <span class="price">420.000 VND</span> BLUE <br>
            <a href="enquire.php" class="buy">Buy</a> </li>
          <li class="last"> <span class="shoe_img"><img src="images/shoes8a.jpg" alt="">
            <p> 
              Gender: Unisex <br>
              Size run: 35 – 46 <br>
              Upper: Canvas/Suede/Leather <br>
              Outsole: Rubber <br>              
            </p>
          </span> <span class="price">610.000 VND</span> DUSTY <br><br>
            <a href="enquire.php" class="buy">Buy</a> </li>
        </ul>
        <aside>
          <h2>A short message from us</h2>
          <p id="aside_p">Introducing our new line of shoes! Perfect for those who demand both style and comfort. With a sleek design and durable construction, our shoes are made to last. Whether you're hitting the streets or heading to the office, our shoes will take you there in style. With a range of colors and sizes, there's a pair for everyone. Don't settle for just any shoes, upgrade your footwear game with our new line. Order now and step into the future with confidence!</p>
        </aside>
      </section>
      <section>
        <table class="table">
          <tr>
            <td>Men</td>
            <td>5</td>
            <td>6</td>
            <td>7</td>
            <td>8</td>
            <td>9</td>
            <td>10</td>
            <td>11</td>
            <td>12</td>
            <td>13</td>
          </tr>
          <tr>
            <td>Women</td>
            <td>6.5</td>
            <td>7.5</td>
            <td>8.5</td>
            <td>9.5</td>
            <td>10.5</td>
            <td>11.5</td>
            <td>12.5</td>
            <td>13.5</td>
            <td>14.5</td>
          </tr>
          <tr>
            <td>EU</td>
            <td>37</td>
            <td>38</td>
            <td>39</td>
            <td>41</td>
            <td>42</td>
            <td>43</td>
            <td>44</td>
            <td>45</td>
            <td>46</td>
          </tr>
        </table>
      </section>
      </div>
    </div>
    <!-- /#contents -->
    <div id="footer">
      <div id="description">
        <div> 
          <a href="index.php" class="logo"></a> 
        </div>
        <p> We're The Shoesroom from class COS10026.2 at Swinburne University. My team has 4 members who are Tran Hoang Hai Anh, Nguyen Tuan Duc, Nguyen Manh Dung and Nguyen Tran Yen Binh. Our group decided to create a web selling shoes. We built this website to provide customers another option for a shoes sale website since there is a high demand for the footwear business and there are now only a few websites selling shoes worldwide.  </p>
      </div>
      <div class="navigation"> <a href="index.php">Home</a>| <a href="enhancement.php">Ehancement</a>|<a href="product.php">Shop</a>| <a
          href="enquire.php">Enquire</a>|  <a href="contact-us.php">Contact</a> </div>
    </div>
    <!-- /#footer -->
  </div>
  <!-- /#page -->
</div>
<!-- /#background -->